<?xml version="1.0" encoding="utf-8"?><Database Name="QLMuaBanSach" Class="QLMuaBanSachDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DangKhoa;Initial Catalog=QLMuaBanSach;Integrated Security=True" SettingsObjectName="QuanLyMuaBanSach.Properties.Settings" SettingsPropertyName="QLMuaBanSachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MaSach" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="HoaDon_CTHD" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sach_CTHD" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Username" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LoaiTaiKhoan" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Association Name="KhachHang_TaiKhoan" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuDat" Member="CTPhieuDats">
    <Type Name="CTPhieuDat">
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MaPhieuDat" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSach" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PhieuDatSach_CTPhieuDat" Member="PhieuDatSach" ThisKey="MaPhieuDat" OtherKey="MaPhieuDat" Type="PhieuDatSach" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sach_CTPhieuDat" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuNhap" Member="CTPhieuNhaps">
    <Type Name="CTPhieuNhap">
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MaSach" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPhieuNhap" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PhieuNhapSach_CTPhieuNhap" Member="PhieuNhapSach" ThisKey="MaPhieuNhap" OtherKey="MaPhieuNhap" Type="PhieuNhapSach" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sach_CTPhieuNhap" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLapHD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_CTHD" Member="CTHDs" ThisKey="MaHD" OtherKey="MaHD" Type="CTHD" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSach" Member="LoaiSaches">
    <Type Name="LoaiSach">
      <Column Name="MaLoai" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="LoaiSach_Sach" Member="Saches" ThisKey="MaLoai" OtherKey="MaLoai" Type="Sach" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="NhaCungCap_PhieuNhapSach" Member="PhieuNhapSaches" ThisKey="MaNCC" OtherKey="MaNCC" Type="PhieuNhapSach" />
    </Type>
  </Table>
  <Table Name="dbo.NhaXuatBan" Member="NhaXuatBans">
    <Type Name="NhaXuatBan">
      <Column Name="MaNXB" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="NhaXuatBan_Sach" Member="Saches" ThisKey="MaNXB" OtherKey="MaNXB" Type="Sach" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDatSach" Member="PhieuDatSaches">
    <Type Name="PhieuDatSach">
      <Column Name="MaPhieuDat" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDatSach_CTPhieuDat" Member="CTPhieuDats" ThisKey="MaPhieuDat" OtherKey="MaPhieuDat" Type="CTPhieuDat" />
      <Association Name="KhachHang_PhieuDatSach" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhapSach" Member="PhieuNhapSaches">
    <Type Name="PhieuNhapSach">
      <Column Name="MaPhieuNhap" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuNhapSach_CTPhieuNhap" Member="CTPhieuNhaps" ThisKey="MaPhieuNhap" OtherKey="MaPhieuNhap" Type="CTPhieuNhap" />
      <Association Name="NhaCungCap_PhieuNhapSach" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NhanVien_PhieuNhapSach" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="MaSach" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DonGiaNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DonGiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTG" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoai" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="MaNXB" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Association Name="Sach_CTHD" Member="CTHDs" ThisKey="MaSach" OtherKey="MaSach" Type="CTHD" />
      <Association Name="Sach_CTPhieuDat" Member="CTPhieuDats" ThisKey="MaSach" OtherKey="MaSach" Type="CTPhieuDat" />
      <Association Name="Sach_CTPhieuNhap" Member="CTPhieuNhaps" ThisKey="MaSach" OtherKey="MaSach" Type="CTPhieuNhap" />
      <Association Name="LoaiSach_Sach" Member="LoaiSach" ThisKey="MaLoai" OtherKey="MaLoai" Type="LoaiSach" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NhaXuatBan_Sach" Member="NhaXuatBan" ThisKey="MaNXB" OtherKey="MaNXB" Type="NhaXuatBan" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TacGia_Sach" Member="TacGia" ThisKey="MaTG" OtherKey="MaTG" Type="TacGia" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TacGia" Member="TacGias">
    <Type Name="TacGia">
      <Column Name="MaTG" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="TacGia_Sach" Member="Saches" ThisKey="MaTG" OtherKey="MaTG" Type="Sach" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SDT" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="KhachHang_TaiKhoan" Member="TaiKhoans" ThisKey="MaKH" OtherKey="MaKH" Type="TaiKhoan" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="MaKH" OtherKey="MaKH" Type="HoaDon" />
      <Association Name="KhachHang_PhieuDatSach" Member="PhieuDatSaches" ThisKey="MaKH" OtherKey="MaKH" Type="PhieuDatSach" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SDT" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ChucVu" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="MaNV" OtherKey="MaNV" Type="TaiKhoan" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDon" />
      <Association Name="NhanVien_PhieuNhapSach" Member="PhieuNhapSaches" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuNhapSach" />
    </Type>
  </Table>
</Database>